---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bazzite
description: This is my personal bazzite image.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: chezmoi
    repository: "https://github.com/ndowens/dotfiles.git"
    all-users: true
    file-conflict-policy: replace

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: user
        install:
          - eu.betterbird.Betterbird

  - type: dnf
  - from-file: dnf.yml
  - from-file: remove-packages.yml

  - type: files
    files:
      - source: system
        destination: /

  - type: justfiles
    validate: false

  - type: script
    snippets:
      - "setsebool -P domain_kernel_load_modules on"
    scripts:
      - hyperland.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: "8h"

  - type: systemd
    system:
      enabled:
        - libvirtd.service
        - podman.socket
    user:
      enabled:
        - chezmoi-init.service
        - chezmoi-update.timer
        - ssh-agent.service
