---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bazzite
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: dnf
  - from-file: install-packages.yml

  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    notify: true
    system:
      install:
        - eu.betterbird.Betterbird
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: script
    snippets:
      - "setsebool -P domain_kernel_load_modules on"

  - type: chezmoi
    repository: "https://github.com/ndowens/dotfiles.git"
    all-users: true
    file-conflict-policy: replace

  - type: systemd
    system:
      disabled:
        - tailscaled
      enabled:
        - podman.socket
        - libvirtd.service
    user:
      enabled:
        - chezmoi-init.service
        - chezmoi-update.timer

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: "8h"
